### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jacksoneshbaugh** [JitHubApp/JitHubV2#52]
I seem to be unable to authenticate with the web component of this app. I simply get a message stating "Authorization failed, please try again." I'm not sure why this isn't working, but I'm certainly excited to try out JitHub. If I can provide any other info, don't hesitate to let me know. Thanks!

**Comment by nerocui** [comment]
Hi @JavaGuy12 , thanks for reporting this bug! I'm sorry it's not working for you. Do you mind taking a look at the console and see what type of error message is showing please?

**Comment by nerocui** [comment]
@JavaGuy12 Just did some investigation, and turns out there's some bug in our server config. Just fixed it. Please give it a try now. I'll close this for now, but feel free to reopen if you still run into the same issue.
